### ISSUE TITLE
Renamed Conjure types result in leftover (old) generated files

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-conjure#172]
## What happened?

If you define a conjure type, run `./gradlew compileConjureObjects`, then rename the type and run `./gradlew compileConjureObjects` again, you'll end up with both the old and the new name in your `src/generated/java` directory.

This is especially dangerous when combined with the build-cache, because it means a `git clean -xdf` may restore the same overloaded cache again and again.  Users may then write code that compiles against the _old_ type, see compilation pass locally, and then have it fail on CI because the old type doesn't exist.

cc @ashrayjain

## What did you want to happen?

The `src/generated/java` directory should be _minimal_ any extraneous files should be deleted automatically!

**Comment by alec-heif** [comment]
confirming this is pretty painful.. in fact I think the following workflow actually has me stuck:

1) change the default package for a set of conjure defs and services: you will now have java files generated under both the old and new packages.

2) change some of the object def names - there are now new-named classes under the new package, and old-named classes under the old package. other classes under the new package will use the new names, but the old java files (which are still generated) use the old classes. 

3) build cache for `api-objects` expires, but the cache for `api-retrofit` does not. your old-package retrofit classes will now reference old-named objects defs which no longer exist. all local builds will now fail because the old-package retrofit classes won't compile due to the nonexistent old objects classes that are still referenced.

aware that this is quite an edge case, but it's pretty unfortunate because my local builds are now all failing due to the generated code referencing classes which no longer exist, and I haven't been able to figure out a workaround (deleting the old generated retrofit classes just results in them getting regenerated).

**Comment by alec-heif** [comment]
update: running with `--no-build-cache` flag has saved the day

**Comment by CRogers** [comment]
~~Seem to get a possibly related version of this where for example changing the package in a conjure typescript file grabs from the build cache rather than rerunning locally. Seems like there could be some issues with the caching settings on task inputs?~~

<img width="1159" alt="Screen Shot 2019-08-21 at 12 25 45 PM" src="https://user-images.githubusercontent.com/397795/63429650-903ec900-c412-11e9-8d0f-be4c4a20f1f5.png">

Looks like it was a @iamdanfox said with the extra files being included in the cached data.

**Comment by ferozco** [comment]
Closed by #185
